import { Scheme } from '../types/schemes.types.js';

export const SEEDED_DEMO_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    title: 'PM Kisan Samman Nidhi',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'subsidy',
    state: 'Central',
    description: 'Direct income support of ₹6,000 per year in three equal installments to eligible farmer families across India.',
    eligibilityCriteria: ['Small & marginal landholding farmers', 'Valid land ownership documents', 'Aadhaar linked bank account'],
    requiredDocuments: ['Aadhaar Card', 'Land Record (Khata/Khasra)', 'Bank Passbook'],
    officialUrl: 'https://pmkisan.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Visit pmkisan.gov.in and register as a new farmer', 'Submit Aadhaar, land record and bank details']
  },
  {
    id: 'pmfby',
    title: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'insurance',
    state: 'Central',
    description: 'Comprehensive crop insurance coverage against natural risk from pre-sowing to post-harvest with low subsidized premiums.',
    eligibilityCriteria: ['All farmers growing notified crops in notified areas', 'Sharecroppers & tenant farmers eligible'],
    requiredDocuments: ['Proposal form', 'Land possession certificate/LPC', 'Sowing certificate', 'Bank passbook'],
    officialUrl: 'https://pmfby.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Apply through bank branch, CSC center or PMFBY portal', 'Pay low subsidized farmer premium (1.5-2% of sum insured)']
  },
  {
    id: 'kisan-credit-card',
    title: 'Kisan Credit Card (KCC) Scheme',
    department: 'NABARD & Reserve Bank of India',
    category: 'loan',
    state: 'Central',
    description: 'Provides timely institutional credit to farmers for agricultural inputs, crop production, and post-harvest maintenance at subsidized interest rates (4% effective).',
    eligibilityCriteria: ['Individual farmers/joint borrowers', 'Tenant farmers, sharecroppers & SHGs', 'Owner cultivators'],
    requiredDocuments: ['Duly filled KCC application form', 'Identity & address proof (Aadhaar/Voter ID)', 'Land holding documents'],
    officialUrl: 'https://www.nabard.org/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Submit completed KCC application to any commercial or rural bank', 'Provide land and identity verification documents']
  },
  {
    id: 'soil-health-card',
    title: 'Soil Health Card Scheme',
    department: 'Department of Agriculture & Farmers Welfare',
    category: 'subsidy',
    state: 'Central',
    description: 'Issues comprehensive soil health cards to farmers with crop-wise nutrient recommendations to optimize fertilizer application and improve soil productivity.',
    eligibilityCriteria: ['All landholding farmers across India'],
    requiredDocuments: ['Aadhaar Card', 'Land plot Khasra number'],
    officialUrl: 'https://soilhealth.dac.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Local agriculture officer collects soil sample from farm plot', 'Receive diagnostic card with customized dosage advice']
  },
  {
    id: 'pmksy-per-drop-more-crop',
    title: 'PM Krishi Sinchayee Yojana (Micro Irrigation)',
    department: 'Ministry of Agriculture / State Agri Depts',
    category: 'equipment',
    state: 'Central',
    description: 'Financial subsidy up to 55% for small/marginal farmers for installing drip and sprinkler micro-irrigation systems.',
    eligibilityCriteria: ['Farmers owning agricultural land with available water source', 'Preference to small & marginal farmers'],
    requiredDocuments: ['Aadhaar Card', 'Land Record (ROR)', 'Electricity connection / water source proof'],
    officialUrl: 'https://pmksy.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Apply on State Horticulture/Micro-Irrigation portal', 'Select empanelled vendor for system installation']
  },
  {
    id: 'agri-infra-fund',
    title: 'Agriculture Infrastructure Fund (AIF)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'loan',
    state: 'Central',
    description: 'Medium-long term debt financing facility for investment in post-harvest infrastructure projects with 3% per annum interest subvention up to ₹2 Crore.',
    eligibilityCriteria: ['Primary Agricultural Credit Societies (PACS)', 'Farmer Producer Organizations (FPOs)', 'Agri-entrepreneurs & individual farmers'],
    requiredDocuments: ['Project Report / DPR', 'KYC documents', 'Land ownership / lease agreement'],
    officialUrl: 'https://agriinfra.dac.gov.in/',
    eligibility: { minLandSize: 0.5, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Register on AIF online portal', 'Submit DPR and choose preferred lending institution']
  },
  {
    id: 'e-nam-scheme',
    title: 'National Agriculture Market (e-NAM)',
    department: 'Small Farmers Agribusiness Consortium (SFAC)',
    category: 'subsidy',
    state: 'Central',
    description: 'Pan-India electronic trading portal networking existing APMC mandis to create a unified national market for agricultural commodities.',
    eligibilityCriteria: ['All farmers selling agricultural produce'],
    requiredDocuments: ['Aadhaar Card', 'Bank account details', 'Mandi registration details'],
    officialUrl: 'https://www.enam.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Register online as a farmer trader on e-NAM', 'Bring produce to notified e-NAM mandi for assaying and online bidding']
  },
  {
    id: 'pkvy-organic',
    title: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'subsidy',
    state: 'Central',
    description: 'Financial assistance of ₹50,000 per hectare over 3 years for organic farming cluster adoption, PGS certification, and organic input production.',
    eligibilityCriteria: ['Farmers forming organic clusters (minimum 20 hectares/farmers)'],
    requiredDocuments: ['Cluster registration form', 'Aadhaar Card', 'Land record copy'],
    officialUrl: 'https://pgsindia-ncof.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 10, states: ['All'], crops: ['Organic', 'Vegetables', 'Pulses', 'Spices', 'All'] },
    applySteps: ['Form farmer cluster with regional council', 'Register cluster on PGS-India organic portal']
  },
  {
    id: 'smam-machinery',
    title: 'Sub-Mission on Agricultural Mechanization (SMAM)',
    department: 'Department of Agriculture & Farmers Welfare',
    category: 'equipment',
    state: 'Central',
    description: 'Provides 40% to 50% subsidy for purchasing tractors, power tillers, combine harvesters, and specialized farm implements.',
    eligibilityCriteria: ['Small, marginal, SC/ST, and women farmers given priority'],
    requiredDocuments: ['Aadhaar Card', 'Land Record (7/12 or Khasra)', 'Bank Passbook', 'Equipment quotation'],
    officialUrl: 'https://agrimachinery.nic.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Register on Direct Benefit Transfer in Agricultural Mechanization portal (agrimachinery.nic.in)', 'Select equipment manufacturer and claim subsidy online']
  },
  {
    id: 'pm-kusum-solar',
    title: 'PM-KUSUM Solar Pump Scheme',
    department: 'Ministry of New & Renewable Energy',
    category: 'equipment',
    state: 'Central',
    description: '60% total subsidy (30% Central + 30% State) for installing standalone solar agriculture pumps up to 7.5 HP in off-grid rural areas.',
    eligibilityCriteria: ['Individual farmers, water user associations, and cooperatives'],
    requiredDocuments: ['Aadhaar Card', 'Land Ownership document', 'Bank passbook', 'Electricity discom NOC'],
    officialUrl: 'https://pmkusum.mnre.gov.in/',
    eligibility: { minLandSize: 0.5, maxLandSize: 9999, states: ['All'], crops: ['All'] },
    applySteps: ['Apply through designated State Renewable Energy Agency portal', 'Deposit 10% farmer contribution after portal verification']
  },
  {
    id: 'pm-matsya-sampada',
    title: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY)',
    department: 'Department of Fisheries',
    category: 'subsidy',
    state: 'Central',
    description: 'Financial support (40% general, 60% SC/ST/women) for fish pond construction, aquaculture inputs, and biofloc units.',
    eligibilityCriteria: ['Fishers, fish farmers, fish workers, and aquaculture entrepreneurs'],
    requiredDocuments: ['Aadhaar Card', 'Land/Pond ownership or lease document', 'Project proposal'],
    officialUrl: 'https://pmmsy.dof.gov.in/',
    eligibility: { minLandSize: 0.2, maxLandSize: 9999, states: ['All'], crops: ['Fisheries', 'Aquaculture', 'All'] },
    applySteps: ['Submit DPR to District Fisheries Development Officer', 'Receive sanction and claim DBT subsidy post inspection']
  },
  {
    id: 'national-beekeeping-mission',
    title: 'National Beekeeping & Honey Mission (NBHM)',
    department: 'National Bee Board / Ministry of Agriculture',
    category: 'subsidy',
    state: 'Central',
    description: 'Up to 80% financial assistance for purchasing bee hives, colonies, honey extraction equipment, and processing infrastructure.',
    eligibilityCriteria: ['Individual farmers, honey producers, and FPOs'],
    requiredDocuments: ['Aadhaar Card', 'NBB registration details', 'Bank Passbook'],
    officialUrl: 'https://nbb.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['All'], crops: ['Honey', 'Horticulture', 'All'] },
    applySteps: ['Register on Madhukranti portal of National Bee Board', 'Submit project plan for apiary setup']
  },
  {
    id: 'bhumihin-krishak-bandhu',
    title: 'Bhumihin Krishak Bandhu (Landless Farmer Scheme)',
    department: 'West Bengal Dept. of Agriculture',
    category: 'subsidy',
    state: 'West Bengal',
    description: 'Targeted annual direct financial assistance for landless agricultural laborers in West Bengal who work on farm lands but possess no title.',
    eligibilityCriteria: ['Landless agricultural laborer resident in West Bengal', 'Zero agricultural land ownership'],
    requiredDocuments: ['Aadhaar Card', 'Bank Account details', 'Self-declaration of landless status'],
    officialUrl: 'https://krishakbandhu.wb.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 0, states: ['West Bengal'], crops: ['All'] },
    applySteps: ['Apply at local Duare Sarkar camp or Block Development Office', 'Submit self-declaration and bank details']
  },
  {
    id: 'krishak-bandhu',
    title: 'Krishak Bandhu (Assistance & Death Benefit)',
    department: 'West Bengal Dept. of Agriculture',
    category: 'subsidy',
    state: 'West Bengal',
    description: 'Assured financial assistance up to ₹10,000/year per acre in two seasonal installments, plus ₹2 Lakh family death benefit cover.',
    eligibilityCriteria: ['Farmers and registered sharecroppers (Bhagchasi) in West Bengal'],
    requiredDocuments: ['Aadhaar Card', 'Land Record (RoR/Khatian) or Sharecropper Certificate', 'Bank Passbook'],
    officialUrl: 'https://krishakbandhu.wb.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['West Bengal'], crops: ['All'] },
    applySteps: ['Submit Krishak Bandhu application at BDO or ADA office', 'Provide Khatian or Bhagchasi registration proof']
  },
  {
    id: 'fssm-wb',
    title: 'Farm Mechanization Subsidy Scheme (FSSM)',
    department: 'West Bengal Dept. of Agriculture',
    category: 'equipment',
    state: 'West Bengal',
    description: '50% to 60% capital subsidy (up to ₹3 Lakh) for small and marginal West Bengal farmers buying power tillers, reapers, and seed drills.',
    eligibilityCriteria: ['Small and marginal farmers in West Bengal owning up to 5 acres'],
    requiredDocuments: ['Aadhaar Card', 'Land Record', 'Quotation from authorized dealer'],
    officialUrl: 'https://matirkatha.net/',
    eligibility: { minLandSize: 0.1, maxLandSize: 5, states: ['West Bengal'], crops: ['All'] },
    applySteps: ['Apply online on Matir Katha portal during application window', 'Upload equipment quotation and land proof']
  },
  {
    id: 'bangla-shasya',
    title: 'Bangla Shasya Bima (BSB)',
    department: 'West Bengal Dept. of Agriculture',
    category: 'insurance',
    state: 'West Bengal',
    description: 'Fully state-sponsored crop insurance scheme where West Bengal government pays 100% of the premium for notified crops.',
    eligibilityCriteria: ['All farmers (owner, sharecropper, tenant) cultivating notified crops in West Bengal'],
    requiredDocuments: ['Aadhaar Card', 'Land Record / Crop Cultivation Certificate from Gram Panchayat', 'Bank Details'],
    officialUrl: 'https://banglashasyabima.net/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['West Bengal'], crops: ['Paddy', 'Wheat', 'Jute', 'Potato', 'Sugarcane', 'All'] },
    applySteps: ['Enroll via local Krishi Bhavan, BDO office, or Gram Panchayat', 'Zero premium payable by the farmer']
  },
  {
    id: 'amar-fasal',
    title: 'Amar Fasal Amar Gola / Amar Gari',
    department: 'West Bengal Dept. of Agriculture',
    category: 'subsidy',
    state: 'West Bengal',
    description: 'Capital subsidy for constructing low-cost grain storage structures (Gola) or purchasing mobile vending carts (Gari) to reduce post-harvest decay.',
    eligibilityCriteria: ['Small & marginal vegetable, fruit, and grain growers in West Bengal'],
    requiredDocuments: ['Aadhaar Card', 'Land Record', 'Bank Account'],
    officialUrl: 'https://matirkatha.net/',
    eligibility: { minLandSize: 0.1, maxLandSize: 5, states: ['West Bengal'], crops: ['Vegetables', 'Fruits', 'Grains', 'All'] },
    applySteps: ['Apply online via Matir Katha or at Block Agriculture Office']
  },
  {
    id: 'rythu-bandhu-telangana',
    title: 'Rythu Bandhu Investment Support Scheme',
    department: 'Department of Agriculture, Telangana',
    category: 'subsidy',
    state: 'Telangana',
    description: 'Financial incentive of ₹10,000 per acre per year (₹5,000 per crop season) directly credited for purchasing seeds, fertilizers, and field prep inputs.',
    eligibilityCriteria: ['Pattadar landowning farmers in Telangana'],
    requiredDocuments: ['Pattadar Passbook', 'Aadhaar Card', 'Bank Account'],
    officialUrl: 'https://rythubandhu.telangana.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['Telangana'], crops: ['All'] },
    applySteps: ['Automatic DBT dispatch based on verified Pattadar Passbook database']
  },
  {
    id: 'yry-rythu-bharosa-ap',
    title: 'YSR Rythu Bharosa - PM KISAN',
    department: 'Department of Agriculture, Andhra Pradesh',
    category: 'subsidy',
    state: 'Andhra Pradesh',
    description: 'Combined financial assistance of ₹13,500 per year for farmer families in Andhra Pradesh (including tenant farmers & ROFR landholders).',
    eligibilityCriteria: ['Landowning farmer families and tenant farmers in Andhra Pradesh'],
    requiredDocuments: ['Aadhaar Card', 'Land passbook / CCRC tenant agreement', 'Bank details'],
    officialUrl: 'https://rythubharosa.ap.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['Andhra Pradesh'], crops: ['All'] },
    applySteps: ['Enrolment verified through Rythu Bharosa Kendras (RBKs) at village level']
  },
  {
    id: 'krushak-odisha',
    title: 'KALIA Scheme (Krushak Assistance for Livelihood)',
    department: 'Department of Agriculture & Farmers Empowerment, Odisha',
    category: 'subsidy',
    state: 'Odisha',
    description: 'Financial support of ₹10,000 per farm family per year for small/marginal farmers and ₹12,500 for landless agricultural households in Odisha.',
    eligibilityCriteria: ['Small/marginal farmers and landless agricultural households in Odisha'],
    requiredDocuments: ['Aadhaar Card', 'Land Document / Ration Card', 'Bank Passbook'],
    officialUrl: 'https://kalia.odisha.gov.in/',
    eligibility: { minLandSize: 0, maxLandSize: 9999, states: ['Odisha'], crops: ['All'] },
    applySteps: ['Apply on KALIA portal or at local Gram Panchayat office']
  },
  {
    id: 'magel-tyala-shettalo-mh',
    title: 'Magel Tyala Shettalo (Farm Pond Scheme)',
    department: 'Department of Agriculture, Maharashtra',
    category: 'equipment',
    state: 'Maharashtra',
    description: 'Subsidy up to ₹50,000 directly credited for constructing individual farm ponds to secure protective irrigation in rainfed farming belts.',
    eligibilityCriteria: ['Farmers in Maharashtra owning minimum 0.6 acres land'],
    requiredDocuments: ['7/12 land extract', '8-A extract', 'Aadhaar Card', 'Bank Passbook'],
    officialUrl: 'https://mahadbt.maharashtra.gov.in/',
    eligibility: { minLandSize: 0.6, maxLandSize: 9999, states: ['Maharashtra'], crops: ['All'] },
    applySteps: ['Register on MahaDBT portal under Farmer Schemes section', 'Select farm pond component and upload land records']
  },
  {
    id: 'mukhya-mantri-kisan-sahay-gj',
    title: 'Mukhyamantri Kisan Sahay Yojana',
    department: 'Department of Agriculture, Gujarat',
    category: 'insurance',
    state: 'Gujarat',
    description: 'State-funded zero-premium crop compensation scheme offering assistance up to ₹20,000/hectare for crop losses caused by drought or unseasonal rain.',
    eligibilityCriteria: ['All landholding farmers in Gujarat registered in 8-A land record'],
    requiredDocuments: ['8-A land certificate', '7/12 extract', 'Aadhaar Card', 'Bank passbook'],
    officialUrl: 'https://ikhedut.gujarat.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['Gujarat'], crops: ['All'] },
    applySteps: ['Submit compensation application on i-Khedut portal when disaster is notified']
  },
  {
    id: 'solar-pump-haryana',
    title: 'Solar Water Pumping Scheme (PM-KUSUM Component)',
    department: 'Department of Renewable Energy, Haryana (HAREDA)',
    category: 'equipment',
    state: 'Haryana',
    description: '75% subsidy for installing 3 HP to 10 HP solar submersible water pumps for agricultural irrigation.',
    eligibilityCriteria: ['Farmers in Haryana without existing grid pump connections'],
    requiredDocuments: ['Aadhaar Card', 'Jamabandi land document', 'Micro-irrigation declaration'],
    officialUrl: 'https://hareda.gov.in/',
    eligibility: { minLandSize: 0.5, maxLandSize: 9999, states: ['Haryana'], crops: ['All'] },
    applySteps: ['Apply on Saral Haryana portal (saralharyana.gov.in)', 'Pay farmer contribution share after document approval']
  },
  {
    id: 'punjab-crop-residue-management',
    title: 'Crop Residue Management (CRM) Subsidy',
    department: 'Department of Agriculture, Punjab',
    category: 'equipment',
    state: 'Punjab',
    description: '50% individual subsidy and 80% Custom Hiring Centre subsidy for purchasing Happy Seeders, Super Seeders, and Paddy Straw Choppers.',
    eligibilityCriteria: ['Farmers & Custom Hiring Centers in Punjab'],
    requiredDocuments: ['Aadhaar Card', 'Jamabandi land record', 'Bank Passbook'],
    officialUrl: 'https://agripunjab.gov.in/',
    eligibility: { minLandSize: 0.5, maxLandSize: 9999, states: ['Punjab'], crops: ['Paddy', 'Wheat', 'All'] },
    applySteps: ['Apply on Punjab Agri Machinery portal', 'Purchase equipment from empanelled manufacturer']
  },
  {
    id: 'up-kisan-karj-rahat',
    title: 'Kisan Rin Mochan Yojana / KCC Interest Subsidy',
    department: 'Department of Agriculture, Uttar Pradesh',
    category: 'loan',
    state: 'Uttar Pradesh',
    description: '3% additional interest subvention and crop loan waiver assistance for small and marginal landholders holding valid KCC accounts.',
    eligibilityCriteria: ['Small and marginal farmers in Uttar Pradesh with active KCC loans'],
    requiredDocuments: ['KCC account number', 'Aadhaar Card', 'Khatauni land record'],
    officialUrl: 'https://upkisankarjrahat.upsdc.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 5, states: ['Uttar Pradesh'], crops: ['All'] },
    applySteps: ['Verify eligibility status on UP Kisan Karj Rahat portal using Aadhaar / KCC account']
  },
  {
    id: 'bihar-diesel-anudan',
    title: 'Bihar Agriculture Input Subsidy / Diesel Anudan',
    department: 'Department of Agriculture, Bihar',
    category: 'subsidy',
    state: 'Bihar',
    description: 'Financial subsidy per acre directly transferred to farmers for purchasing diesel irrigation inputs or replacing storm-damaged crops.',
    eligibilityCriteria: ['Actual landowning and tenant cultivators in Bihar'],
    requiredDocuments: ['Aadhaar Card', 'LPC land document / Tenant declaration', 'Diesel purchase receipt'],
    officialUrl: 'https://dbtagriculture.bihar.gov.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['Bihar'], crops: ['Paddy', 'Maize', 'Pulses', 'All'] },
    applySteps: ['Apply online at dbtagriculture.bihar.gov.in', 'Upload diesel voucher and field detail']
  },
  {
    id: 'chhattisgarh-godhan-nyay',
    title: 'Rajiv Gandhi Kisan Nyay Yojana',
    department: 'Department of Agriculture, Chhattisgarh',
    category: 'subsidy',
    state: 'Chhattisgarh',
    description: 'Direct income support of ₹9,000 per acre to paddy, sugarcane, pulse, and oilseed growing farmers in Chhattisgarh.',
    eligibilityCriteria: ['Farmers in Chhattisgarh cultivating notified Kharif/Rabi crops'],
    requiredDocuments: ['Aadhaar Card', 'Khasra/B-1 document', 'Bank account details'],
    officialUrl: 'https://rgkny.cg.nic.in/',
    eligibility: { minLandSize: 0.1, maxLandSize: 9999, states: ['Chhattisgarh'], crops: ['Paddy', 'Pulses', 'Oilseeds', 'Sugarcane', 'All'] },
    applySteps: ['Register crop details on RGKNY portal through Rural Agriculture Extension Officer']
  }
];
