import {
  WeatherData,
  FloodRiskAssessment,
  ClimateAssessmentResult,
  AssessmentHistoryItem,
  FoodSecuritySnapshot,
  DistrictRiskItem,
  ScenarioSimulationResult,
  GeocodeResult,
  AiInsightResult,
  GeminiDecisionPlan,
  GovtGeminiDecisionPlan
} from './types';

export class ClimateRiskService {
  /**
   * Fetches personalized live AI Decision Plan generated by Gemini
   */
  static async fetchGeminiDecision(payload: {
    location: string;
    crop: string;
    cropStage: string;
    language?: string;
    lat?: number;
    lon?: number;
    completedActions?: string[];
    previousRisk?: any;
  }): Promise<GeminiDecisionPlan> {
    try {
      const res = await fetch('/api/climate-risk/decision', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('[ClimateRiskService] Backend Gemini decision endpoint unreachable, using client smart engine:', err);
    }

    // Client fallback decision generator
    return this.generateSmartClientDecision(payload.location, payload.crop, payload.cropStage, payload.language || 'en', payload.completedActions || []);
  }

  /**
   * Fetches Government Food Security AI Decision Plan generated by Gemini
   */
  static async fetchGovtGeminiDecision(payload: {
    state?: string;
    district?: string;
    location?: string;
    crop?: string;
    cropStage?: string;
    language?: string;
    rainfallMm?: number;
    floodRisk?: string;
    lossPercentage?: number;
    transportAccessibility?: string;
    storageAvailability?: string;
  }): Promise<GovtGeminiDecisionPlan> {
    try {
      const res = await fetch('/api/climate-risk/govt-decision', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('[ClimateRiskService] Backend Govt Gemini decision endpoint unreachable, using fallback:', err);
    }

    const lang = (payload.language || 'en').toLowerCase();
    const rainfallMm = Number(payload.rainfallMm ?? 45);
    const floodRisk = payload.floodRisk || 'HIGH';
    const lossPercentage = Number(payload.lossPercentage ?? 30);
    const isHighRain = rainfallMm > 25 || floodRisk === 'HIGH' || floodRisk === 'SEVERE' || lossPercentage >= 25;
    const crop = payload.crop || 'Paddy';

    if (lang === 'bn') {
      if (isHighRain) {
        return {
          planTitle: 'সরকারি সংগ্রহ পরিকল্পনা',
          subtitle: 'AI-সংগৃহীত ফসল সংগ্রহ ও পরিবহন পরিকল্পনা',
          riskSummary: `🌾 ভারী বৃষ্টির আগে ${crop === 'Wheat' ? 'গম' : 'ধান'} সংগ্রহে গুরুত্ব দিন। ভারী বৃষ্টিতে ফসল কাটা ও পরিবহন ব্যাহত হতে পারে।`,
          hasUrgentAction: true,
          actions: [
            { id: 'g-1', priority: 'HIGH', title: `${crop === 'Wheat' ? 'গম' : 'ধান'} সংগ্রহে অগ্রাধিকার দিন`, description: `বৃষ্টির আগে প্রস্তুত ${crop === 'Wheat' ? 'গম' : 'ধান'} সংগ্রহ করুন।`, timing: 'বৃষ্টির আগে', icon: 'procurement' },
            { id: 'g-2', priority: 'HIGH', title: 'পরিবহনের ব্যবস্থা করুন', description: 'রাস্তা খারাপ হওয়ার আগে ফসল সরান।', timing: 'বৃষ্টির আগে', icon: 'transport' },
            { id: 'g-3', priority: 'IMPORTANT', title: 'গুদাম পরীক্ষা করুন', description: 'আসা ফসলের জন্য শুকনো জায়গা রাখুন।', timing: 'এই সপ্তাহে', icon: 'storage' },
            { id: 'g-4', priority: 'NORMAL', title: 'সরবরাহ পর্যবেক্ষণ করুন', description: 'স্থানীয় ফসলের প্রাপ্যতা ট্র্যাক করুন।', timing: 'প্রতিদিন', icon: 'monitor' }
          ],
          procurementNeeds: [
            { item: `🌾 ${crop === 'Wheat' ? 'গম' : 'ধান'}`, need: 'উচ্চ চাহিদা', urgency: 'HIGH' },
            { item: '🚛 পরিবহন', need: 'আগে ব্যবস্থা করুন', urgency: 'HIGH' },
            { item: '🏠 গুদাম', need: 'ধারণক্ষমতা পরীক্ষা করুন', urgency: 'IMPORTANT' }
          ],
          transportAlert: {
            show: true,
            title: '⚠️ পরিবহন সতর্কতা',
            text: 'ভারী বৃষ্টিতে ফসল পরিবহন ধীর হতে পারে। দ্রুত পরিবহনের ব্যবস্থা করুন।'
          },
          storageAlert: {
            show: true,
            title: '🏠 গুদাম',
            text: 'আসা ফসলের জন্য শুকনো সংরক্ষণের জায়গা প্রয়োজন হতে পারে।'
          },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      } else {
        return {
          planTitle: 'সরকারি সংগ্রহ পরিকল্পনা',
          subtitle: 'AI-সংগৃহীত ফসল সংগ্রহ ও পরিবহন পরিকল্পনা',
          riskSummary: 'খাদ্যশস্য সরবরাহ ও স্থানীয় মজুদ স্থিতিশীল রয়েছে।',
          hasUrgentAction: false,
          actions: [
            { id: 'g-1', priority: 'NORMAL', title: 'নিয়মিত সংগ্রহ পর্যবেক্ষণ', description: 'মান্দি ও সংগ্রহ কেন্দ্রে স্বাভাবিক কাজ রাখুন।', timing: 'দৈনিক', icon: 'procurement' },
            { id: 'g-2', priority: 'NORMAL', title: 'মজুদ সমীক্ষা করুন', description: 'জেলা গুদামের মজুদের হিসাব নিন।', timing: 'এই সপ্তাহে', icon: 'storage' }
          ],
          procurementNeeds: [
            { item: `🌾 ${crop === 'Wheat' ? 'গম' : 'ধান'}`, need: 'স্বাভাবিক সংগ্রহ', urgency: 'NORMAL' },
            { item: '🏠 গুদাম', need: 'পর্যাপ্ত জায়গা', urgency: 'NORMAL' }
          ],
          transportAlert: { show: false, text: '' },
          storageAlert: { show: false, text: '' },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      }
    } else if (lang === 'hi') {
      if (isHighRain) {
        return {
          planTitle: 'सरकारी खरीद योजना',
          subtitle: 'AI-जनित खरीद और परिवहन योजना',
          riskSummary: `🌾 भारी बारिश से पहले ${crop === 'Wheat' ? 'गेहूं' : 'धान'} की खरीद पर ध्यान दें। बारिश से कटाई और परिवहन प्रभावित हो सकता है।`,
          hasUrgentAction: true,
          actions: [
            { id: 'g-1', priority: 'HIGH', title: `${crop === 'Wheat' ? 'गेहूं' : 'धान'} खरीद को प्राथमिकता दें`, description: `बारिश से पहले तैयार ${crop === 'Wheat' ? 'गेहूं' : 'धान'} खरीदें।`, timing: 'बारिश से पहले', icon: 'procurement' },
            { id: 'g-2', priority: 'HIGH', title: 'परिवहन की व्यवस्था करें', description: 'सड़क खराब होने से पहले फसल पहुंचाएं।', timing: 'बारिश से पहले', icon: 'transport' },
            { id: 'g-3', priority: 'IMPORTANT', title: 'भंडारण जांचें', description: 'आने वाली फसल के लिए सूखी जगह रखें।', timing: 'इस सप्ताह', icon: 'storage' },
            { id: 'g-4', priority: 'NORMAL', title: 'आपूर्ति पर नजर रखें', description: 'स्थानीय फसल उपलब्धता ट्रैक करें।', timing: 'रोजाना', icon: 'monitor' }
          ],
          procurementNeeds: [
            { item: `🌾 ${crop === 'Wheat' ? 'गेहूं' : 'धान'}`, need: 'उच्च आवश्यकता', urgency: 'HIGH' },
            { item: '🚛 परिवहन', need: 'पहले व्यवस्था करें', urgency: 'HIGH' },
            { item: '🏠 भंडारण', need: 'क्षमता की जांच करें', urgency: 'IMPORTANT' }
          ],
          transportAlert: {
            show: true,
            title: '⚠️ परिवहन चेतावनी',
            text: 'भारी बारिश से फसल की आवाजाही धीमी हो सकती है। पहले परिवहन का प्रबंध करें।'
          },
          storageAlert: {
            show: true,
            title: '🏠 भंडारण',
            text: 'आने वाली उपज के लिए सूखे भंडारण की आवश्यकता हो सकती है।'
          },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      } else {
        return {
          planTitle: 'सरकारी खरीद योजना',
          subtitle: 'AI-जनित खरीद और परिवहन योजना',
          riskSummary: 'खाद्यान्न आपूर्ति और स्थानीय भंडार सुरक्षित स्थिति में है।',
          hasUrgentAction: false,
          actions: [
            { id: 'g-1', priority: 'NORMAL', title: 'नियमित खरीद निगरानी', description: 'मंडियों में सामान्य खरीद जारी रखें।', timing: 'रोजाना', icon: 'procurement' },
            { id: 'g-2', priority: 'NORMAL', title: 'भंडार का निरीक्षण करें', description: 'जिला गोदामों की स्थिति देखें।', timing: 'इस सप्ताह', icon: 'storage' }
          ],
          procurementNeeds: [
            { item: `🌾 ${crop === 'Wheat' ? 'गेहूं' : 'धान'}`, need: 'सामान्य खरीद', urgency: 'NORMAL' },
            { item: '🏠 भंडारण', need: 'पर्याप्त स्थान', urgency: 'NORMAL' }
          ],
          transportAlert: { show: false, text: '' },
          storageAlert: { show: false, text: '' },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      }
    }

    // Default: English
    if (isHighRain) {
      return {
        planTitle: 'GOVERNMENT PROCUREMENT PLANNER',
        subtitle: 'AI-generated procurement and transport plan',
        riskSummary: `🌾 ${crop} procurement may need early action. Heavy rain may affect harvesting and transport.`,
        hasUrgentAction: true,
        actions: [
          { id: 'g-1', priority: 'HIGH', title: 'Prioritize local procurement', description: `Secure mature ${crop.toLowerCase()} before heavy rain.`, timing: 'Before rain', icon: 'procurement' },
          { id: 'g-2', priority: 'HIGH', title: 'Arrange transport', description: 'Move harvested crops before roads worsen.', timing: 'Before rain', icon: 'transport' },
          { id: 'g-3', priority: 'IMPORTANT', title: 'Check storage', description: 'Prepare dry storage for incoming crops.', timing: 'This week', icon: 'storage' },
          { id: 'g-4', priority: 'NORMAL', title: 'Monitor supply', description: 'Track local crop availability.', timing: 'Daily', icon: 'monitor' }
        ],
        procurementNeeds: [
          { item: `🌾 ${crop}`, need: 'High need', urgency: 'HIGH' },
          { item: '🚛 Transport', need: 'Arrange early', urgency: 'HIGH' },
          { item: '🏠 Storage', need: 'Check capacity', urgency: 'IMPORTANT' }
        ],
        transportAlert: {
          show: true,
          title: '⚠️ TRANSPORT ALERT',
          text: 'Heavy rain may slow crop movement. Arrange transport early.'
        },
        storageAlert: {
          show: true,
          title: '🏠 STORAGE',
          text: 'Dry storage may be needed for incoming crops.'
        },
        updatedAt: new Date().toISOString(),
        source: 'RULE_BASED'
      };
    } else {
      return {
        planTitle: 'GOVERNMENT PROCUREMENT PLANNER',
        subtitle: 'AI-generated procurement and transport plan',
        riskSummary: 'Crop procurement and grain availability remain in normal operating balance.',
        hasUrgentAction: false,
        actions: [
          { id: 'g-1', priority: 'NORMAL', title: 'Maintain regular procurement', description: 'Continue standard mandi procurement operations.', timing: 'Daily', icon: 'procurement' },
          { id: 'g-2', priority: 'NORMAL', title: 'Inspect buffer storage', description: 'Review grain inventory in district godowns.', timing: 'This week', icon: 'storage' }
        ],
        procurementNeeds: [
          { item: `🌾 ${crop}`, need: 'Normal procurement', urgency: 'NORMAL' },
          { item: '🏠 Storage', need: 'Adequate capacity', urgency: 'NORMAL' }
        ],
        transportAlert: { show: false, text: '' },
        storageAlert: { show: false, text: '' },
        updatedAt: new Date().toISOString(),
        source: 'RULE_BASED'
      };
    }
  }

  /**
   * Client-side Smart Gemini Decision Generator fallback with English, Bengali, and Hindi
   */
  static generateSmartClientDecision(
    location: string = 'Haldia, West Bengal',
    crop: string = 'Paddy',
    cropStage: string = 'Flowering',
    language: string = 'en',
    completedActions: string[] = []
  ): GeminiDecisionPlan {
    const isHaldia = location.toLowerCase().includes('haldia') || location.toLowerCase().includes('bengal');
    const isMaturity = cropStage.toLowerCase().includes('maturity') || cropStage.toLowerCase().includes('ready') || cropStage.toLowerCase().includes('harvest');
    const isFlowering = cropStage.toLowerCase().includes('flowering');
    const isSowing = cropStage.toLowerCase().includes('sowing') || cropStage.toLowerCase().includes('seedling');
    const isPotato = crop.toLowerCase().includes('potato');

    const isRainy = isHaldia;
    const riskLevel = isRainy ? 'HIGH' : 'LOW';

    if (language === 'bn') {
      if (isRainy) {
        const actions: any[] = [];
        if (!completedActions.includes('act-1') && !completedActions.includes('drainage')) {
          actions.push({ id: 'act-1', priority: 'HIGH', title: isPotato ? 'নালা ও খাল পরিষ্কার করুন' : 'নালা পরিষ্কার করুন', description: 'বৃষ্টির আগে নালা পরিষ্কার করুন।', timing: 'আজকের মধ্যে', icon: 'drainage' });
        }
        if (isMaturity) {
          actions.push({ id: 'act-2', priority: 'HIGH', title: 'পাকা ফসল কাটুন', description: 'বৃষ্টির আগে পাকা ফসল কেটে নিন।', timing: '১–২ দিনের মধ্যে', icon: 'harvest' });
          actions.push({ id: 'act-3', priority: 'IMPORTANT', title: 'ফসল নিরাপদ স্থানে রাখুন', description: 'ফসল শুকনো ও উঁচু জায়গায় রাখুন।', timing: 'বৃষ্টির আগে', icon: 'protect' });
        } else {
          actions.push({ id: 'act-2', priority: 'IMPORTANT', title: isFlowering ? 'স্প্রে বন্ধ রাখুন' : 'সার প্রয়োগ বন্ধ রাখুন', description: 'ভারী বৃষ্টির আগে স্প্রে বা সার দেবেন না।', timing: 'বৃষ্টির আগে', icon: 'spray' });
          actions.push({ id: 'act-3', priority: 'IMPORTANT', title: 'প্রয়োজনীয় জিনিস কিনুন', description: 'সার ও কীটনাশক আগে কিনুন।', timing: 'বৃষ্টির আগে', icon: 'cart' });
        }
        if (actions.length < 4) {
          actions.push({ id: 'act-4', priority: 'NORMAL', title: 'নিচু জমি ও আল দেখুন', description: 'নিচু জমি ও দুর্বল আল পরীক্ষা করুন।', timing: 'আজকের মধ্যে', icon: 'tools' });
        }

        return {
          riskLevel: 'HIGH',
          riskTitle: 'ভারী বৃষ্টির সম্ভাবনা',
          riskTimeline: 'পরবর্তী ৩–৫ দিন',
          riskSummary: 'ভারী বৃষ্টির সম্ভাবনা। জমিতে জল জমতে পারে।',
          aiExplanation: isMaturity ? `${crop} কাটার সময় হয়েছে। বৃষ্টির আগে পাকা ফসল কেটে নিরাপদ স্থানে রাখুন।` : `${cropStage} অবস্থায় ${crop} গাছে জল জমলে ক্ষতি হবে। নিকাশি ব্যবস্থা ঠিক রাখুন।`,
          whyReasoningSummary: `আপনার ${crop} ফসলের ${cropStage} অবস্থায় ভারী বৃষ্টি হতে পারে বলে এই ব্যবস্থাগুলি জরুরি।`,
          decisionFactors: [`পরবর্তী ৩–৫ দিনে ভারী বৃষ্টি (৫৭ মিমি)`, `${crop} ফসল বর্তমানে ${cropStage} অবস্থায় আছে`, `নিচু জমিতে জল জমার ঝুঁকি বেশি`],
          actions,
          buyItems: isMaturity ? [
            { name: 'তিরপল ও ত্রিপল কভার', reason: 'তোলা ফসল ভিজে নষ্ট হওয়া থেকে বাঁচান', urgency: 'HIGH', category: 'tools' },
            { name: 'শুকনো বস্তা', reason: 'আর্দ্রতার হাত থেকে শস্য রক্ষা করুন', urgency: 'NORMAL', category: 'tools' }
          ] : [
            { name: 'ছত্রাকনাশক স্প্রে', reason: 'বৃষ্টির পরে ব্লাইট রোগ প্রতিরোধে', urgency: 'HIGH', category: 'pesticides' },
            { name: 'জরুরি সার স্টক (ইউরিয়া/ডিএপি)', reason: 'রাস্তা বন্ধের আগেই সংগ্রহ করুন', urgency: 'HIGH', category: 'fertilizer' },
            { name: 'কোদাল ও নিকাশি সরঞ্জাম', reason: 'নালা পরিষ্কার রাখার জন্য', urgency: 'NORMAL', category: 'tools' }
          ],
          whyBuyNow: 'ভারী বৃষ্টিতে রাস্তা বন্ধ হতে পারে। আগে প্রয়োজনীয় জিনিস কিনে রাখা ভালো।',
          warning: { show: true, title: 'সতর্কবার্তা', headline: 'ভারী বৃষ্টিতে রাস্তা চলাচল কঠিন হতে পারে।', subtext: 'প্রয়োজনীয় কৃষি সরঞ্জাম ও সার আগে কিনে নিন।' },
          weatherSummary: { temperature: 29, condition: 'ভারী বৃষ্টি', rainfallProbability: 86, expectedRainfallMm: 57 },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      } else {
        return {
          riskLevel: 'LOW',
          riskTitle: 'স্বাভাবিক আবহাওয়া',
          riskTimeline: 'পরবর্তী ৫–৭ দিন',
          riskSummary: 'আবহাওয়া স্থিতিশীল। নিয়মিত চাষের কাজ চালিয়ে যান।',
          aiExplanation: `${cropStage} অবস্থায় ${crop} ফসলের জন্য আবহাওয়া অনুকূল। নিয়মিত পরিচর্যা করুন।`,
          whyReasoningSummary: `আবহাওয়া স্বাভাবিক থাকায় নিয়মিত কৃষি কাজের পরামর্শ দেওয়া হয়েছে।`,
          decisionFactors: [`বৃষ্টির সম্ভাবনা কম (১৫%)`, `${crop} ফসল ${cropStage} অবস্থায় আছে`, `বন্যা বা ঝড়ের ঝুঁকি নেই`],
          actions: [
            { id: 'act-1', priority: 'NORMAL', title: 'নিয়মিত সেচ দিন', description: `${crop} ফসলে পরিমিত জল সরবরাহ বজায় রাখুন।`, timing: 'নিয়মমাফিক', icon: 'monitor' },
            { id: 'act-2', priority: 'NORMAL', title: 'কীটপতঙ্গ পরীক্ষা করুন', description: 'পাতার তলায় পোকার আক্রমণ লক্ষ্য করুন।', timing: '২ দিনের মধ্যে', icon: 'spray' }
          ],
          buyItems: [],
          whyBuyNow: 'স্বাভাবিক আবহাওয়ায় বাজারে সঠিক দামে পণ্য পাওয়া যায়।',
          warning: { show: false, title: '', headline: '', subtext: '' },
          weatherSummary: { temperature: 28, condition: 'পরিষ্কার আকাশ', rainfallProbability: 15, expectedRainfallMm: 0 },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      }
    } else if (language === 'hi') {
      if (isRainy) {
        const actions: any[] = [];
        if (!completedActions.includes('act-1') && !completedActions.includes('drainage')) {
          actions.push({ id: 'act-1', priority: 'HIGH', title: isPotato ? 'नालियां व मेड़ साफ करें' : 'नालियां साफ करें', description: 'बारिश से पहले नालियां साफ करें।', timing: 'आज ही', icon: 'drainage' });
        }
        if (isMaturity) {
          actions.push({ id: 'act-2', priority: 'HIGH', title: 'पकी फसल काटें', description: 'बारिश से पहले पकी फसल निकाल लें।', timing: '१–२ दिन में', icon: 'harvest' });
          actions.push({ id: 'act-3', priority: 'IMPORTANT', title: 'फसल सुरक्षित जगह रखें', description: 'उपज को सूखे और ऊंचे स्थान पर रखें।', timing: 'बारिश से पहले', icon: 'protect' });
        } else {
          actions.push({ id: 'act-2', priority: 'IMPORTANT', title: isFlowering ? 'स्प्रे रोकें' : 'खाद डालना रोकें', description: 'भारी बारिश से पहले स्प्रे न करें।', timing: 'बारिश से पहले', icon: 'spray' });
          actions.push({ id: 'act-3', priority: 'IMPORTANT', title: 'जरूरी सामान खरीदें', description: 'खाद और दवा पहले खरीदें।', timing: 'बारिश से पहले', icon: 'cart' });
        }
        if (actions.length < 4) {
          actions.push({ id: 'act-4', priority: 'NORMAL', title: 'नीचे वाले खेत देखें', description: 'निचले खेतों और मेड़ों की जांच करें।', timing: 'आज ही', icon: 'tools' });
        }

        return {
          riskLevel: 'HIGH',
          riskTitle: 'भारी बारिश की संभावना',
          riskTimeline: 'अगले ३–५ दिन',
          riskSummary: 'भारी बारिश की संभावना है। खेतों में पानी भर सकता है।',
          aiExplanation: isMaturity ? `${crop} फसल कटाई के करीब है। बारिश से पहले पकी फसल को सुरक्षित स्थान पर ले जाएं।` : `${cropStage} अवस्था में जलजमाव से ${crop} को नुकसान हो सकता है। जल निकासी दुरुस्त रखें।`,
          whyReasoningSummary: `आपकी ${crop} फसल की ${cropStage} अवस्था में बारिश के खतरे को देखते हुए ये सुझाव दिए गए हैं।`,
          decisionFactors: [`अगले ३–५ दिनों में तेज बारिश (५७ मिमी)`, `${crop} फसल अभी ${cropStage} अवस्था में है`, `खेत में जलभराव का खतरा अधिक है`],
          actions,
          buyItems: isMaturity ? [
            { name: 'तिरपाल व वाटरप्रूफ कवर', reason: 'कटी फसल को भीगने से बचाएं', urgency: 'HIGH', category: 'tools' },
            { name: 'सूखी बोरियां', reason: 'नमी से अनाज को सुरक्षित रखें', urgency: 'NORMAL', category: 'tools' }
          ] : [
            { name: 'फफूंदनाशक दवा', reason: 'बारिश के बाद फफूंद रोग रोकने के लिए', urgency: 'HIGH', category: 'pesticides' },
            { name: 'उर्वरक स्टॉक (यूरिया/डीएपी)', reason: 'रास्ते बंद होने से पहले मंगाएं', urgency: 'HIGH', category: 'fertilizer' },
            { name: 'फावड़ा व निकासी औजार', reason: 'नालियां खुली रखने के लिए', urgency: 'NORMAL', category: 'tools' }
          ],
          whyBuyNow: 'भारी बारिश से रास्ते खराब हो सकते हैं। जरूरी कृषि इनपुट पहले से खरीद लें।',
          warning: { show: true, title: 'चेतावनी', headline: 'सड़क पर आवाजाही कठिन हो सकती है।', subtext: 'पहले ही जरूरी खाद व बीज का इंतजाम कर लें।' },
          weatherSummary: { temperature: 29, condition: 'तेज बारिश', rainfallProbability: 86, expectedRainfallMm: 57 },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      } else {
        return {
          riskLevel: 'LOW',
          riskTitle: 'सामान्य मौसम',
          riskTimeline: 'अगले ५–७ दिन',
          riskSummary: 'मौसम साफ है। नियमित खेती कार्य जारी रखें।',
          aiExplanation: `${cropStage} अवस्था में ${crop} के लिए मौसम अनुकूल है। नियमित देखभाल करें।`,
          whyReasoningSummary: `मौसम स्थिर रहने के कारण सामान्य कार्य जारी रखने का सुझाव है।`,
          decisionFactors: [`बारिश की संभावना कम (१५%)`, `${crop} फसल ${cropStage} अवस्था में है`, `बाढ़ का कोई खतरा नहीं`],
          actions: [
            { id: 'act-1', priority: 'NORMAL', title: 'नियमित सिंचाई करें', description: `${crop} फसल में जरूरत अनुसार नमी बनाए रखें।`, timing: 'समय अनुसार', icon: 'monitor' },
            { id: 'act-2', priority: 'NORMAL', title: 'कीट व रोगों की जांच करें', description: 'पत्तियों पर कीटों के प्रकोप पर नजर रखें।', timing: '२ दिन में', icon: 'spray' }
          ],
          buyItems: [],
          whyBuyNow: 'सामान्य मौसम में बाजार में इनपुट सही दामों पर उपलब्ध रहते हैं।',
          warning: { show: false, title: '', headline: '', subtext: '' },
          weatherSummary: { temperature: 28, condition: 'साफ मौसम', rainfallProbability: 15, expectedRainfallMm: 0 },
          updatedAt: new Date().toISOString(),
          source: 'RULE_BASED'
        };
      }
    }

    // Default: English
    if (isRainy) {
      const actions: any[] = [];
      if (!completedActions.includes('act-1') && !completedActions.includes('drainage')) {
        actions.push({
          id: 'act-1',
          priority: 'HIGH',
          title: isPotato ? 'Clear furrows & drains' : 'Clear blocked drains',
          description: 'Clear drains before rain.',
          timing: 'Today',
          icon: 'drainage'
        });
      }

      if (isMaturity) {
        actions.push({
          id: 'act-2',
          priority: 'HIGH',
          title: `Harvest mature ${crop}`,
          description: 'Harvest mature crop early.',
          timing: 'Next 1–2 days',
          icon: 'harvest'
        });
        actions.push({
          id: 'act-3',
          priority: 'IMPORTANT',
          title: 'Protect harvested crop',
          description: 'Move harvest to dry storage.',
          timing: 'Before rain',
          icon: 'protect'
        });
      } else {
        actions.push({
          id: 'act-2',
          priority: 'IMPORTANT',
          title: isFlowering ? 'Stop spraying' : 'Stop applying fertilizer',
          description: 'Stop spraying before heavy rain.',
          timing: 'Before rain',
          icon: 'spray'
        });
        actions.push({
          id: 'act-3',
          priority: 'IMPORTANT',
          title: 'Buy needed inputs',
          description: 'Buy needed inputs before rain.',
          timing: 'Before rain',
          icon: 'cart'
        });
      }

      if (actions.length < 4) {
        actions.push({
          id: 'act-4',
          priority: 'NORMAL',
          title: 'Check low fields',
          description: 'Check weak bunds and low fields.',
          timing: 'Today',
          icon: 'tools'
        });
      }

      return {
        riskLevel: 'HIGH',
        riskTitle: 'Heavy Rain Likely',
        riskTimeline: 'Next 3–5 days',
        riskSummary: 'High chance of heavy rainfall. Fields may get waterlogged.',
        aiExplanation: isMaturity
          ? `${crop} is near harvest. Harvest mature sections early and store safely.`
          : `${crop} at ${cropStage.toLowerCase()} stage is vulnerable to water stagnation. Keep drains clear.`,
        whyReasoningSummary: `Gemini recommends these actions because heavy rainfall is expected during the ${cropStage.toLowerCase()} stage of your ${crop} crop.`,
        decisionFactors: [
          `Heavy rain expected in next 3–5 days (57 mm peak)`,
          `${crop} is currently at the ${cropStage} stage`,
          `High waterlogging risk in low-lying plots`
        ],
        actions,
        buyItems: isMaturity ? [
          { name: 'Waterproof Tarpaulins', reason: 'Protect harvested grain from rain', urgency: 'HIGH', category: 'tools' },
          { name: 'Storage Bags', reason: 'Keep produce dry in humidity', urgency: 'NORMAL', category: 'tools' }
        ] : [
          { name: 'Bio-Fungicide Spray', reason: 'Prevent fungal blast after rain', urgency: 'HIGH', category: 'pesticides' },
          { name: 'Fertilizer Stock (Urea/DAP)', reason: 'Buy before roads get blocked', urgency: 'HIGH', category: 'fertilizer' },
          { name: 'Drainage Tools', reason: 'Useful for channel clearing', urgency: 'NORMAL', category: 'tools' }
        ],
        whyBuyNow: 'Heavy rain may make roads difficult. Buying essential inputs before rainfall reduces delays.',
        warning: {
          show: true,
          title: 'WARNING',
          headline: 'Road access may worsen.',
          subtext: 'Buy needed inputs before rain.'
        },
        weatherSummary: {
          temperature: 29,
          condition: 'Heavy Rain Likely',
          rainfallProbability: 86,
          expectedRainfallMm: 57
        },
        updatedAt: new Date().toISOString(),
        source: 'RULE_BASED'
      };
    } else {
      const actions: any[] = [];
      if (isSowing) {
        actions.push({
          id: 'act-1',
          priority: 'IMPORTANT',
          title: `Prepare ${crop} seedbed`,
          description: 'Conditions are good for seed sowing.',
          timing: 'This week',
          icon: 'seed'
        });
        actions.push({
          id: 'act-2',
          priority: 'NORMAL',
          title: 'Procure certified seed',
          description: 'Treat seed before sowing.',
          timing: 'Next 2–3 days',
          icon: 'cart'
        });
      } else if (isMaturity) {
        actions.push({
          id: 'act-1',
          priority: 'HIGH',
          title: `Schedule ${crop} harvest`,
          description: 'Sunny weather is ideal for harvest.',
          timing: 'Next 1–3 days',
          icon: 'harvest'
        });
        actions.push({
          id: 'act-2',
          priority: 'NORMAL',
          title: 'Prepare clean storage',
          description: 'Inspect bags for mandi transport.',
          timing: 'Before harvest',
          icon: 'protect'
        });
      } else {
        actions.push({
          id: 'act-1',
          priority: 'NORMAL',
          title: 'Maintain regular irrigation',
          description: `Provide optimum moisture for ${crop}.`,
          timing: 'As per schedule',
          icon: 'monitor'
        });
        actions.push({
          id: 'act-2',
          priority: 'NORMAL',
          title: 'Inspect for pests',
          description: 'Check leaves for pest symptoms.',
          timing: 'Next 2 days',
          icon: 'spray'
        });
        actions.push({
          id: 'act-3',
          priority: 'NORMAL',
          title: 'Apply micronutrients',
          description: `Support growth during ${cropStage.toLowerCase()} phase.`,
          timing: 'This week',
          icon: 'fertilizer'
        });
      }

      return {
        riskLevel: 'LOW',
        riskTitle: 'Stable Weather Conditions',
        riskTimeline: 'Next 5–7 days',
        riskSummary: 'Normal weather expected. Continue regular farm activities.',
        aiExplanation: `Weather conditions remain manageable for ${crop} at ${cropStage.toLowerCase()} stage. Continue regular work.`,
        whyReasoningSummary: `Gemini recommends regular farm routines as weather forecasts show stable conditions.`,
        decisionFactors: [
          `Low rain probability (15%)`,
          `${crop} is currently at ${cropStage} stage`,
          `No flood or storm hazards detected`
        ],
        actions,
        buyItems: isSowing ? [
          { name: `Certified ${crop} Seeds`, reason: 'Quality tested seed stock', urgency: 'NORMAL', category: 'seeds' },
          { name: 'Basal Fertilizer', reason: 'Nutrients for seedbed preparation', urgency: 'NORMAL', category: 'fertilizer' }
        ] : [],
        whyBuyNow: 'Stable weather ensures standard mandi prices and open roads.',
        warning: { show: false, title: '', headline: '', subtext: '' },
        weatherSummary: {
          temperature: 28,
          condition: 'Partly Sunny',
          rainfallProbability: 15,
          expectedRainfallMm: 0
        },
        updatedAt: new Date().toISOString(),
        source: 'RULE_BASED'
      };
    }
  }

  /**
   * Geocodes query into coordinates via Open-Meteo backend endpoint
   */
  static async geocodeLocation(query: string): Promise<GeocodeResult[]> {
    if (!query || query.trim().length < 2) return [];
    try {
      const res = await fetch(`/api/climate-risk/geocode?q=${encodeURIComponent(query.trim())}`);
      if (res.ok) {
        const json = await res.json();
        if (json.success && Array.isArray(json.data)) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('Geocoding endpoint unreachable:', err);
    }
    return [];
  }

  /**
   * Fetches AI decision insight via backend OpenRouter AiClient
   */
  static async fetchAiInsight(payload: {
    location: string;
    crop: string;
    cropStage: string;
    overallRiskScore: number;
    floodScore: number;
    cropRiskScore: number;
    harvestCode: string;
    rainfallMm: number;
    mainThreat?: string;
  }): Promise<AiInsightResult> {
    try {
      const res = await fetch('/api/climate-risk/ai-insight', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('AI insight endpoint unreachable:', err);
    }
    return {
      headline: payload.overallRiskScore >= 70
        ? `${payload.mainThreat || 'Heavy rainfall'} is the dominant near-term agricultural risk.`
        : `Weather conditions remain manageable for ${payload.crop} at ${payload.cropStage} stage.`,
      severity: payload.overallRiskScore >= 70 ? 'SEVERE' : payload.overallRiskScore >= 45 ? 'MODERATE' : 'LOW',
      actions: payload.overallRiskScore >= 70
        ? ['Protect field drainage channels immediately', 'Avoid spray/fertilizer applications before rain', 'Inspect low-lying plots & prepare harvest logistics']
        : ['Continue regular crop monitoring', 'Maintain optimal irrigation schedule', 'Ensure field drainage exits are cleared'],
      timing: 'Next 24–48 hours',
      source: 'RULE_BASED'
    };
  }

  /**
   * Fetches complete weather, flood risk, and climate assessment telemetry
   */
  static async fetchFullAssessment(
    location: string = 'Haldia, West Bengal',
    crop: string = 'Paddy',
    cropStage: string = 'Flowering',
    lat?: number,
    lon?: number
  ): Promise<{ weather: WeatherData; flood: FloodRiskAssessment; assessment: ClimateAssessmentResult }> {
    try {
      const res = await fetch('/api/climate-risk/assessment', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ location, crop, cropStage, lat, lon })
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('Backend API unreachable, using client-side fallback engine:', err);
    }

    // Client-side Fallback Generator if Server API is offline
    return this.generateFallbackAssessment(location, crop, cropStage);
  }

  /**
   * Fetches Food Security Snapshot overview
   */
  static async fetchFoodSecurityOverview(
    state: string = 'West Bengal',
    crop: string = 'Paddy'
  ): Promise<FoodSecuritySnapshot> {
    try {
      const res = await fetch(`/api/food-security/overview?state=${encodeURIComponent(state)}&crop=${encodeURIComponent(crop)}`);
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('Backend Food Security API unreachable, using fallback:', err);
    }

    const currentStock = 8.4;
    const expectedProduction = 11.2;
    const estimatedClimateLoss = 3.1;
    const committedOutwardSupply = 8.0;
    const safetyThreshold = 7.2;
    const projectedDomesticAvailability = Number((currentStock + expectedProduction - estimatedClimateLoss - committedOutwardSupply).toFixed(2));

    return {
      id: 'fs-fallback',
      state,
      crop,
      currentStockLakhTonnes: currentStock,
      expectedProductionLakhTonnes: expectedProduction,
      estimatedClimateLossLakhTonnes: estimatedClimateLoss,
      committedOutwardSupplyLakhTonnes: committedOutwardSupply,
      projectedDomesticAvailabilityLakhTonnes: projectedDomesticAvailability,
      safetyStockThresholdLakhTonnes: safetyThreshold,
      riskLevel: projectedDomesticAvailability >= safetyThreshold ? 'NORMAL' : 'CRITICAL',
      advisoryText: 'Domestic supply remains above configured safety threshold. Continue monitoring commitments.',
      recommendedPolicyActions: [
        'Review projected crop losses',
        'Monitor district-level supply',
        'Review outward movement commitments'
      ],
      updatedAt: new Date().toISOString()
    };
  }

  /**
   * Runs dynamic What-If Disaster Scenario simulation
   */
  static async runScenarioSimulation(
    cropLossPercentage: number,
    state: string = 'West Bengal',
    crop: string = 'Paddy'
  ): Promise<ScenarioSimulationResult> {
    try {
      const res = await fetch('/api/food-security/scenario', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cropLossPercentage, state, crop })
      });
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('Scenario API unreachable, calculating locally:', err);
    }

    const currentStock = 8.4;
    const baselineProduction = 11.2;
    const committedOutwardSupply = 8.0;
    const safetyStockThreshold = 7.2;

    const estimatedClimateLoss = Number(((baselineProduction * cropLossPercentage) / 100).toFixed(2));
    const effectiveProduction = Number((baselineProduction - estimatedClimateLoss).toFixed(2));
    const projectedDomesticAvailability = Number(
      (currentStock + effectiveProduction - committedOutwardSupply).toFixed(2)
    );
    const safetyGap = Number((projectedDomesticAvailability - safetyStockThreshold).toFixed(2));

    let riskLevel: 'NORMAL' | 'CAUTION' | 'CRITICAL' = 'NORMAL';
    if (projectedDomesticAvailability < safetyStockThreshold) riskLevel = 'CRITICAL';
    else if (projectedDomesticAvailability < safetyStockThreshold + 1.2) riskLevel = 'CAUTION';

    return {
      cropLossPercentage,
      currentStock,
      baselineProduction,
      estimatedClimateLoss,
      effectiveProduction,
      committedOutwardSupply,
      projectedDomesticAvailability,
      safetyStockThreshold,
      safetyGap,
      riskLevel,
      advisoryHeadline: riskLevel === 'CRITICAL' ? 'CRITICAL SUPPLY DEFICIT' : 'SURPLUS AVAILABILITY',
      tradeAdvisory: riskLevel === 'CRITICAL'
        ? 'Review outward movement and prioritize domestic supply requirements.'
        : 'Domestic supply remains above configured safety threshold.',
      recommendedActions: [
        'Review outward movement/export commitments',
        'Prioritize domestic food-security requirements',
        'Assess regional redistribution requirements'
      ]
    };
  }

  /**
   * Fetches district-wise risk breakdown
   */
  static async fetchDistrictRisks(state: string = 'West Bengal'): Promise<DistrictRiskItem[]> {
    try {
      const res = await fetch(`/api/food-security/districts?state=${encodeURIComponent(state)}`);
      if (res.ok) {
        const json = await res.json();
        if (json.success && json.data) {
          return json.data;
        }
      }
    } catch (err) {
      console.warn('Districts API unreachable, returning demo data:', err);
    }

    return [
      { district: 'Haldia', crop: 'Paddy', cropRiskLevel: 'HIGH', floodRiskLevel: 'SEVERE', estimatedLossPercentage: 35, dataSource: 'Demonstration / simulated data' },
      { district: 'Murshidabad', crop: 'Paddy', cropRiskLevel: 'HIGH', floodRiskLevel: 'HIGH', estimatedLossPercentage: 28, dataSource: 'Demonstration / simulated data' },
      { district: 'Burdwan', crop: 'Paddy', cropRiskLevel: 'MODERATE', floodRiskLevel: 'HIGH', estimatedLossPercentage: 18, dataSource: 'Demonstration / simulated data' },
      { district: 'Kharagpur', crop: 'Paddy', cropRiskLevel: 'LOW', floodRiskLevel: 'MODERATE', estimatedLossPercentage: 10, dataSource: 'Demonstration / simulated data' }
    ];
  }

  /**
   * Fetches historical risk logs
   */
  static async fetchHistory(): Promise<AssessmentHistoryItem[]> {
    return [
      { id: 'h-1', date: '08 Sep 2026', location: 'Haldia, West Bengal', crop: 'Paddy', climateRisk: 'HIGH (72)', floodRisk: 'SEVERE (82)', recommendation: 'Consider early harvest of mature crop' },
      { id: 'h-2', date: '05 Sep 2026', location: 'Haldia, West Bengal', crop: 'Paddy', climateRisk: 'LOW (24)', floodRisk: 'LOW (18)', recommendation: 'Normal harvest operations permitted' },
      { id: 'h-3', date: '01 Sep 2026', location: 'Ludhiana, Punjab', crop: 'Wheat', climateRisk: 'LOW (15)', floodRisk: 'LOW (10)', recommendation: 'Standard field management' }
    ];
  }

  /**
   * Fallback Generator for offline client-side rendering
   */
  private static generateFallbackAssessment(
    location: string,
    crop: string,
    cropStage: string
  ): { weather: WeatherData; flood: FloodRiskAssessment; assessment: ClimateAssessmentResult } {
    const isHaldia = location.toLowerCase().includes('haldia');

    const weather: WeatherData = {
      location: location || 'Haldia, West Bengal',
      latitude: 22.0667,
      longitude: 88.0667,
      temperatureCelsius: 29,
      humidityPercent: 78,
      rainfallProbability: 70,
      expectedRainfallMm: 42,
      windSpeedKmh: 18,
      condition: 'Partly Cloudy',
      feelsLikeCelsius: 32,
      pressureHpa: 1008,
      uvIndex: 6,
      visibilityKm: 8.5,
      updatedAt: new Date().toISOString(),
      source: 'DEMO_FALLBACK',
      hourly: [
        { time: '08:00', temp: 28, rainProb: 75, precipitation: 4.2, windSpeed: 16, condition: 'Heavy Rain' },
        { time: '11:00', temp: 30, rainProb: 80, precipitation: 8.5, windSpeed: 20, condition: 'Thunderstorm' },
        { time: '14:00', temp: 31, rainProb: 65, precipitation: 5.0, windSpeed: 18, condition: 'Rain Showers' },
        { time: '17:00', temp: 29, rainProb: 40, precipitation: 1.2, windSpeed: 14, condition: 'Cloudy' },
        { time: '20:00', temp: 27, rainProb: 20, precipitation: 0.0, windSpeed: 12, condition: 'Partly Cloudy' },
        { time: '23:00', temp: 26, rainProb: 15, precipitation: 0.0, windSpeed: 10, condition: 'Clear' }
      ],
      daily: [
        { date: '2026-09-08', dayName: 'MON', condition: 'Partly Cloudy', minTemp: 28, maxTemp: 34, rainProb: 70, precipitation: 18, windSpeed: 18, severity: 'HIGH' },
        { date: '2026-09-09', dayName: 'TUE', condition: 'Heavy Rain', minTemp: 27, maxTemp: 31, rainProb: 85, precipitation: 46, windSpeed: 22, severity: 'SEVERE' },
        { date: '2026-09-10', dayName: 'WED', condition: 'Thunderstorm', minTemp: 26, maxTemp: 30, rainProb: 90, precipitation: 58, windSpeed: 28, severity: 'SEVERE' },
        { date: '2026-09-11', dayName: 'THU', condition: 'Light Rain', minTemp: 27, maxTemp: 32, rainProb: 50, precipitation: 12, windSpeed: 16, severity: 'MODERATE' },
        { date: '2026-09-12', dayName: 'FRI', condition: 'Cloudy', minTemp: 28, maxTemp: 33, rainProb: 30, precipitation: 4, windSpeed: 14, severity: 'LOW' },
        { date: '2026-09-13', dayName: 'SAT', condition: 'Clear Sky', minTemp: 27, maxTemp: 34, rainProb: 15, precipitation: 0, windSpeed: 12, severity: 'LOW' },
        { date: '2026-09-14', dayName: 'SUN', condition: 'Sunny', minTemp: 28, maxTemp: 35, rainProb: 10, precipitation: 0, windSpeed: 10, severity: 'LOW' }
      ]
    };

    const flood: FloodRiskAssessment = {
      floodScore: isHaldia ? 82 : 45,
      riskLevel: isHaldia ? 'SEVERE' : 'MODERATE',
      reasons: [
        'Heavy rainfall expected within the next 48 hours.',
        'Multiple rainy days forecast.',
        'Area has historical flood susceptibility.',
        'Water level expected to rise in local drainage channels.'
      ],
      timeline: {
        h24: 'MODERATE',
        h48: 'HIGH',
        h72: isHaldia ? 'SEVERE' : 'MODERATE',
        d7: 'LOW'
      },
      dataSource: 'DEMONSTRATION_DATA',
      disclaimer: 'Flood risk is an early-warning assessment, not a guaranteed flood prediction.'
    };

    const assessment: ClimateAssessmentResult = {
      overallRiskScore: 72,
      overallRiskLevel: 'HIGH',
      floodRisk: flood,
      cropRisk: {
        cropName: crop,
        cropStage: cropStage,
        cropRiskScore: 68,
        cropRiskLevel: 'HIGH',
        factors: [
          'Heavy rainfall threat during active crop stage',
          'High exposure to flood conditions and water accumulation',
          'High humidity fungal conducive environment'
        ],
        potentialExposure: 'High potential exposure to excess moisture stress'
      },
      harvestAdvisory: {
        actionCode: 'CONSIDER EARLY HARVEST',
        headline: '⚠️ CONSIDER EARLY HARVEST',
        primaryReason: 'Heavy rainfall is expected within the next 48 hours and the crop is estimated to be near maturity.',
        actionSteps: [
          'Prepare harvesting equipment immediately.',
          'Inspect crop maturity across field sections.',
          'Harvest mature portion before severe rainfall begins.',
          'Move harvested grain to covered, elevated storage.'
        ]
      },
      farmerActionPlan: {
        today: [
          'Inspect field drainage outlets and bunds.',
          'Monitor rain forecast updates.',
          'Avoid applying liquid pesticides or fertilizers before rain.'
        ],
        next24h: [
          'Prepare harvesting equipment and tarpaulins.',
          'Secure dry covered storage space.',
          'Check grain moisture level if crop is mature.'
        ],
        next48h: [
          'Harvest mature crop sections if weather permits.',
          'Transport harvested yield to protected storage.',
          'Do NOT leave harvested produce exposed in open fields.'
        ],
        postEvent: [
          'Inspect field for standing water accumulation.',
          'Drain trapped water from crop roots.',
          'Record crop damage for insurance verification if required.'
        ]
      },
      operationalAdvisories: {
        spraying: { status: 'NOT RECOMMENDED', guidance: 'Not recommended — rain probability is high.' },
        irrigation: { status: 'STOP', guidance: 'Reduce irrigation — sufficient rainfall expected.' },
        fertilizer: { status: 'POSTPONE', guidance: 'Consider postponing application due to heavy rainfall.' },
        fieldWork: { status: 'AVOID', guidance: 'Avoid machinery operation during saturated soil conditions.' },
        drying: { status: 'NOT RECOMMENDED', guidance: 'Outdoor drying is not recommended for the next 24 hours.' }
      },
      procurementAdvisory: {
        riskLevel: 'CAUTION',
        recommendedWindow: 'Delay procurement dispatch by 48 Hours',
        guidance: 'Heavy rainfall may disrupt transportation and increase post-harvest spoilage risk. Prioritize procurement from lower-risk areas.'
      },
      storageAdvisory: {
        riskLevel: 'ELEVATED',
        guidance: 'Move harvested produce to covered storage. High humidity may increase spoilage risk.'
      },
      alerts: [
        {
          id: 'alt-1',
          title: '🌧️ Heavy Rain Alert',
          severity: 'CRITICAL',
          reason: 'Cumulative rainfall of 128 mm expected over next 7 days.',
          recommendedAction: 'Inspect field drainage channels immediately.',
          expectedTimeWindow: 'Next 48 Hours'
        },
        {
          id: 'alt-2',
          title: '🌊 Flood Risk Alert',
          severity: 'CRITICAL',
          reason: 'Flood risk score is 82/100 (SEVERE).',
          recommendedAction: 'Move harvested grain to safe elevated storage.',
          expectedTimeWindow: 'Next 72 Hours'
        }
      ],
      rainfallAnalysis: {
        todayMm: 18,
        tomorrowMm: 46,
        next3DaysMm: 122,
        next7DaysMm: 138,
        total7DayMm: 138,
        maxExpectedMm: 58,
        highestRainfallDay: 'Thursday — 58 mm',
        rainfallRiskLevel: 'HIGH',
        consecutiveRainyDays: 4,
        explanation: 'Heavy rainfall is expected within the next 48 hours.'
      }
    };

    return { weather, flood, assessment };
  }
}
